version: "4.28"
services:
 vite_docker:
   image: node:21.1
   container_name: three_docker
   entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true